variable "redform_key_name" {
  type        = string
  default     = "redform-key-pair"
  description = "Key-pair generated by Redform"
}

variable "ami" {
  type        = string
  # Kali Linux image
  default     = "ami-0895913865fe4ae72"
  description = "The AMI of the server"
}

variable "instance_type" {
  type = string
  default = "t2.micro"
  description = "The type of the EC2 instance to create"
}

variable "instance_name" {
  type = string
  default = "redform-instance"
  description = "The EC2 instance name to set"
}

variable "ssh_user" {
  type        = string
  default     = "kali"
  description = "The username to use while connecting via SSH for provisioning"
}